### PR TITLE
structs for Neural Operators

### LINKED ISSUE #16: Make `DeepONet` and `FourierNeuralOperator` into structs
```julia
deeponet = NeuralOperators.DeepONet(
    Chain(
        Dense(1 => 10, Lux.tanh_fast), Dense(10 => 10, Lux.tanh_fast), Dense(10 => 10)),
    Chain(Dense(1 => 10, Lux.tanh_fast), Dense(10 => 10, Lux.tanh_fast),
        Dense(10 => 10, Lux.tanh_fast)))
julia> deeponet.name ==nothing 
true
```
it guess it should be something like  deeponet.name  == "DeepONet"

### PR DESCRIPTION
**Pull request by ayushinav**
fixes #16

### CODE REVIEW

**Comment by ayushinav** [comment]
I thought overloading `Lux.setup` and defining `model(x, ps, st)` would work without changing anything else but then there are other `Lux` functions that dispatch on a `Lux.AbstractExplictLayer` so maybe we can just always call `model.ch` everywhere?

**Comment by avik-pal** [comment]
> I thought overloading Lux.setup 

That is an invalid overload. It almost certainly won't do what you are expecting it to do.

I don't understand the rest of your question.

**Comment by ayushinav** [comment]
Instead of moving to structs, it is more convinient to make FNOs a compact layer too. I previously had a struct with the chain `ch` as its only parameter. This meant we call `model.ch` everytime, which did not seem very elegant to me, especially for someone using neural operators independently. I overloaded `Lux.setup` and `model(x, ps, st)` but there are other `Lux` functions which take a `model` and it would be somewhat hard to maintain if overload all the required functions.
Finally, moving FNO to compact layer works, and does not require any change in appplying the models.
To dispatch a function on DeepONet, we have `CompactLuxLayer{:DeepONet}` and similarly for FNO: `CompactLuxLayer{:FourierNeuralOperator}`
 In future, we would therefore need to have all the models as `compact` layers or something similar if we want them to be dispatched in a similar way. 
 @avik-pal

**Comment by ayushinav** [comment]
https://github.com/LuxDL/NeuralOperators.jl/pull/19/commits/5b6ce9fc061b669ce0725311000493f0f771d1df#diff-c2cb5b240d81999115bf4cfd0c46952645c08c0b620b37c91e51de853ccb6f51L18-L36

This was the overload I meant.

**Comment by avik-pal** [comment]
No that is not the correct way to define the structs discussed in that issue. Go through https://lux.csail.mit.edu/stable/manual/interface

**Comment by ayushinav** [comment]
I'll move around the docstring. Right now ig they do not correspond to right function calls. 
Also, this might be a good time to convert `OperatorKernel` into struct too.

**Comment by avik-pal** [comment]
Yes let's do that.

**Pull request closed without merging**
